In [2]:
import numpy as np

In [13]:
list1 = [1,2,3]
a = np.array(list1)
print(a.shape)

(3,)


In [7]:
b = np.array([[1,2,3,4], [5,6,7,8]])
print(b.shape)
print(b[0,0])

(2, 4)
1


In [8]:
a = np.zeros((3),dtype = 'int64')
print(a)

[0 0 0]


In [10]:
a = np.zeros((3,3), dtype = "int64")
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [11]:
a = np.ones((3,3), dtype = "int64")
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [12]:
a = np.ones((3),dtype = 'int64')
print(a)

[1 1 1]


In [14]:
a = np.full((3),1,dtype = 'int64')
print(a)

[1 1 1]


In [16]:
a = np.full((3,2,2),1,dtype = 'int64')
print(a)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [17]:
a = np.eye((3))
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
a = np.array(range(12))
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [23]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [24]:
a = np.array(range(12)).reshape(3,-1)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [25]:
a = np.array(range(12)).reshape(-1,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [28]:
list = np.arange(1,10).reshape(3,3)
print(list)
a= list [0:2, 0:2]
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


In [39]:

a = np.array([0, 1, 2, 3])
b = np.arange(12).reshape(3, 4)

print(a[:2])
print(b)

[0 1]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [36]:
print(a[1:])

[1 2 3]


In [37]:
print(a[::-1])

[3 2 1 0]


In [43]:
print(a[1:4:2])

[1 3]


In [44]:
print(b[0][1])
print(b[0,1])
print(b[::2])

1
1
[[ 0  1  2  3]
 [ 8  9 10 11]]


In [46]:
print(b[:2])
print(b[:,0])

[[0 1 2 3]
 [4 5 6 7]]
[0 4 8]


In [48]:
print(b[:,[0,2]])

[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [49]:
print(b[:2,:])

[[0 1 2 3]
 [4 5 6 7]]


In [52]:
print(b[:,[2,0]])

[[ 2  0]
 [ 6  4]
 [10  8]]


In [53]:
print(b[:,[0,2]])

[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [55]:
b_5 = b > 5
print(b_5)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [56]:
print(b[b_5])

[ 6  7  8  9 10 11]


In [57]:
print(b[b>5])

[ 6  7  8  9 10 11]


In [68]:
arr = np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:
a = arr[[0,1],[1,2]]
print(a)

[2 6]


In [67]:
bool_indexing_array = np.array([
    [False,True,False],
    [True,False,True],
    [False,True,False]
])

n = arr[bool_indexing_array]
print(n)

[2 4 6 8]


In [69]:
n = arr[arr % 2 == 0]
print(n)

[2 4 6 8]


In [73]:
a = [0,1,2,3]
b = np.arange(4)
print(a+b)
print(type(a))
print(type(b))

[0 2 4 6]
<class 'list'>
<class 'numpy.ndarray'>


In [76]:
# Shape 변환

In [79]:
a = np.arange(16).reshape(4,-1)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [80]:
np.split(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [84]:
np.split(a, 2, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [87]:
np.split(a, 2, axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [89]:
np.split(a,(1,3)) #[:1],[1:3],[3:]

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [86]:
np.split(a,(1,3), axis = 1)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [91]:
split1, split2 = np.hsplit(a,2) # split1 ,split2 = np.split(a,2, axis =1)
print(split1)
print("=="*30)
print(split2)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [92]:
split1, split2 = np.vsplit(a,2) # split1 ,split2 = np.split(a,2, axis =0)
print(split1)
print("=="*30)
print(split2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [95]:
split1 ,split2 = np.split(a,2, axis =1)
print(split1)
print("=="*30)
print(split2)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Stack 연산

In [98]:
stack0 = np.stack((a,a))
print(stack0.shape)

(2, 4, 4)


In [100]:
print(stack0)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]]


In [103]:
stack1 = np.stack((a,a), axis = 1)
print(stack1.shape)

(4, 2, 4)


In [102]:
print(stack1)

[[[ 0  1  2  3]
  [ 0  1  2  3]]

 [[ 4  5  6  7]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [12 13 14 15]]]


In [104]:
print(np.vstack((a,a))) # axis = 0 방향으로 결합

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [105]:
print(np.hstack((a,a))) # axis = 1 방향으로 결핣

[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]
 [12 13 14 15 12 13 14 15]]


# 일차원 구조로 변경하기

In [110]:
a  = np.arange(16).reshape(4,-1)
print(a.flatten())
print(a.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [117]:
b = a.flatten()
b[0] = 100
c = a.ravel()
c[1] = 200
print(a)
print(c)
print(b)

[[  0 200   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]
[  0 200   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
[100 200   2   3   4   5   6   7   8   9  10  11  12  13  14  15]


In [128]:
a = [1,2,3]
b = [4,5,6]
c = np.subtract(a,b)
print(c)

[-3 -3 -3]


In [133]:
x = np.arange(1,13).reshape(4,-1)
v = np.array([1,0,1])
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [135]:
lst1 = [[1,2],[3,4]]
lst2 = [[1,2],[3,4]]

a = np.array(lst1)
b = np.array(lst2)
c = np.dot(a,b)
print(c)


[[ 7 10]
 [15 22]]


In [136]:
a = np.array([[1,2],[3,4],[5,6]])
s = np.sum(a)
print(s)

s = np.sum(a, axis = 0)
print(s)

s = np.sum(a, axis = 1)
print(s)

21
[ 9 12]
[ 3  7 11]


In [144]:
np.random.seed(0)

In [147]:
np.random.rand(5)

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [149]:
x = np.arange(10)
np.random.shuffle(x)
print(x)

[5 2 7 4 1 0 6 8 9 3]


In [150]:
z = np.random.choice(5,3,replace = False)
print(z)

[1 4 2]


In [154]:
z= np.random.choice(10, 20, replace = True)
print(z)

[4 4 3 4 4 8 4 3 7 5 5 0 1 5 9 3 0 5 0 1]


In [153]:
z = np.random.choice(5,10, p = [0.1,0,0.3,0.6,0])
print(z)

[0 3 3 2 2 2 2 3 3 3]


In [155]:
x = np.random.randint(1,100, size = 5)

In [156]:
print(x)

[51 37 35 49 94]


In [159]:
a = [ 5,1,7,7,2,3,5]
x = np.unique(a)
print(x)

[1 2 3 5 7]


In [160]:
x, cnt = np.unique(a, return_counts = True)
print(x,cnt, sep = ",")

[1 2 3 5 7],[1 1 1 2 2]
